acceptto_mfa/config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

match 'mfa/check', :controller => 'mfa', :action => 'check', :via => :get
match 'mfa/callback', :controller => 'mfa', :action => 'callback', :via => :get
match 'mfa/status', :controller => 'mfa', :action => 'status', :via => :get

acceptto_mfa/app/controllers/mfa_controller.rb
class MfaController < ApplicationController
  unloadable
  skip_before_action :mfa_authentication_required

  def check
    user = User.current
    if user.nil?
      flash[:error] = l(:mfa_user_session_expired)
      return redirect_back_or_default signin_path
    end

    session[:channel] = nil
    user = User.current
    oauth_client = OAuth2::Client.new(Setting.plugin_acceptto_mfa['app_uid'],Setting.plugin_acceptto_mfa['app_secret'], :site => Setting.plugin_acceptto_mfa['mfa_site'])
    access = OAuth2::AccessToken.from_hash(oauth_client, {:access_token => user.mfa_access_token})
    response = access.post('/api/v8/check', { :body => {:channel => params[:channel]}}).parsed
    status = response['status']

    if status == "approved"
      user.update_attribute(:mfa_authenticated, true)
      flash[:notice] = l(:mfa_enable_acceptted)
      return redirect_back_or_default my_page_path
    elsif status == "rejected"
      logout_user
      flash[:error] = l(:mfa_enable_rejected)
      return redirect_back_or_default signin_path
    else
      logout_user
      flash[:error] = l(:mfa_enable_timeout)
      return redirect_back_or_default signin_path
    end
  end

  def callback
    if params[:access_token].blank?
      flash[:error] = l(:mfa_access_denied)
      return redirect_to my_account_path
    end

    user = User.current
    user.mfa_access_token = params[:access_token]
    user.mfa_authenticated = true
    user.save
    flash[:notice] = l(:mfa_access_granted)
    redirect_to my_account_path
  end
end

acceptto_mfa/app/helpers/mfa_helper.rb
module MfaHelper
end

acceptto_mfa/app/views/acceptto_mfa/_account_preferences.html.erb
<p>
	<label><%= l(:label_enable_mfa) %></label>
  <% if !@user.mfa_access_token.present? %>
		<a href='<%= "#{Setting.plugin_acceptto_mfa['mfa_site']}/mfa/email?uid=#{Setting.plugin_acceptto_mfa['app_uid']}&callback_url=#{request.protocol + request.host_with_port}/mfa/callback" %>'><%= l(:mfa_enable_now) %></a>
	<% elsif %>
		<%= l(:mfa_already_enabled) %>
  <% end %>
</p>

acceptto_mfa/app/views/acceptto_mfa/callback.html.erb
<h2>AuthenticationController#callback</h2>

acceptto_mfa/app/views/acceptto_mfa/check.html.erb
<h2>AuthenticationController#check</h2>

acceptto_mfa/app/views/settings/_acceptto_mfa_settings.erb
<table>
  <tbody>
    <tr>
      <th>Acceptto MFA Website</th>
      <td>
        <input type="text" size="45" id="settings_mfa_site"
                           value="<%= settings['mfa_site'] %>"
                           name="settings[mfa_site]" >
      </td>
    </tr>

    <tr>
      <th>Application UID</th>
      <td>
        <input type="text" size="45" id="settings_app_uid"
                           value="<%= settings['app_uid'] %>"
                           name="settings[app_uid]" >
      </td>
    </tr>

    <tr>
      <th>Application Secret</th>
      <td>
        <input type="text" size="45" id="settings_app_secret"
                           value="<%= settings['app_secret'] %>"
                           name="settings[app_secret]" >
      </td>
    </tr>

    <tr>
      <th>Authentication Message</th>
      <td>
        <input type="text" size="45" id="settings_auth_message"
                           value="<%= settings['auth_message'] %>"
                           name="settings[auth_message]" >
      </td>
    </tr>

    <tr>
      <th>Authentication Timeout (Seconds)</th>
      <td>
        <input type="text" size="45" id="settings_auth_timeout"
                           value="<%= settings['auth_timeout'] %>"
                           name="settings[auth_timeout]" >
      </td>
    </tr>

  </tbody>
</table>